export const registred_association=

            [
                    {
                        "_id": "4vDBCheF79nxoz2bo",
                        "eventName": "Whizdata TT Championship",
                        "projectId": [
                            "QvHXDftiwsnc8gyfJ"
                        ],
                        "eventStartDate": "2021 Feb 10",
                        "eventEndDate": "2022 Jan 31",
                        "eventSubscriptionLastDate": "2021 Feb 03",
                        "domainId": [
                            "8va5A8N3EKAeKtmeB"
                        ],
                        "eventOrganizer": "k8oK8G2h2KyrddDd8",
                        "domainName": "Karnataka",
                        "projectName": "Table Tennis",
                        "venueLatitude": "15.3172775",
                        "venueLongitude": "75.7138884",
                        "venueAddress": "Karnataka",
                        "eventStartDate1": "2021-02-10T00:00:00.000Z",
                        "eventEndDate1": "2022-01-31T00:00:00.000Z",
                        "eventSubscriptionLastDate1": "2021-02-03T00:00:00.000Z",
                        "offsetOfDomain": -330,
                        "timeZoneName": "Asia/Kolkata",
                        "timezoneIdEventLat": "15.3172775",
                        "timezoneIdEventLng": "75.7138884",
                        "tournamentEvent": true,
                        "offset": 0,
                        "subscriptionTypeDirect": "1",
                        "subscriptionTypeHyper": "0",
                        "hyperLinkValue": "0",
                        "subscriptionTypeMail": "1",
                        "subscriptionTypeMailValue": "testing@gmail.com",
                        "paymentEntry": "no",
                        "stateAssocId": "k8oK8G2h2KyrddDd8",
                        "eventCreatedDate": "2020-09-03T14:05:22.525Z",
                        "allowSubscription": "yes",
                        "source": "",
                        "eventUpdatedDate": "2020-09-03T14:05:25.432Z",
                        "eventsUnderTournament": [
                            "qJsDnM2vfApjrq4Jq",
                            "F7tc8xHPidTHYY6ra",
                            "8jQinKtnwF9zJvYqg",
                            "utuBA9cTXdzxZ8zXq",
                            "gBTp4SdZPuAajvN8G",
                            "fQudnacFNrtSokEQ6",
                            "mSZhTmqQx3die4zni",
                            "CbBoGsFwaTPwZZoAk",
                            "ApvkjPvEqTsLk98eQ",
                            "ENAGt9iqnwpp7a6DR",
                            "DFbmH6cWfvQ9AJsSb",
                            "9c2mh9RddJwPZKaCA",
                            "4S56MHhTfXfH7j3Qf",
                            "8EsciFWJ9HGj4Gev3",
                            "n8RGqLkGiCwwY5gwC",
                            "TiaMjWMh5ZL4ozWRy"
                        ],
                        "eventsProjectIdUnderTourn": [
                            "kslkebduo27N2uux7",
                            "kscge09m1u7N2uux7",
                            "ksHHDWReSe7N2uux7",
                            "AJ5LtgFtStmL6KgsD",
                            "H8NKgBHk6JYrycCvf",
                            "tXpQ4DwgrAfFGR4oj",
                            "nPnrTCix3yAD3TmAz",
                            "arGJsShtr9sjRXwyT",
                            "nPnrTCix3yAD3TmAzz",
                            "arGJsShtr9sjRXwyTz",
                            "2XMzYon6GbE9TxmGN",
                            "5ioxxYpoPuox8huWC",
                            "Bn9emodsjqgWEi2pK",
                            "giR4SJEhDJ6mtNGW7",
                            "Sv6rNBU8IaiAozRXE",
                            "Sv6rQkgf8pH87NbYZ"
                        ]
                    },
                    {
                        "_id": "T979AX4LbmxzfQ2gi",
                        "eventName": "TT Association Championship 2020",
                        "projectId": [
                            "QvHXDftiwsnc8gyfJ"
                        ],
                        "eventStartDate": "2020 Aug 01",
                        "eventEndDate": "2020 Dec 31",
                        "eventSubscriptionLastDate": "2020 Jul 01",
                        "domainId": [
                            "WdDKtMiDjsc93GeZZ"
                        ],
                        "eventOrganizer": "k8oK8G2h2KyrddDd8",
                        "domainName": "Andaman and Nicobar Islands",
                        "projectName": "Table Tennis",
                        "venueLatitude": "11.7400867",
                        "venueLongitude": "92.6586401",
                        "venueAddress": "Andaman and Nicobar Islands",
                        "eventStartDate1": "2020-08-01T00:00:00.000Z",
                        "eventEndDate1": "2020-12-31T00:00:00.000Z",
                        "eventSubscriptionLastDate1": "2020-07-01T00:00:00.000Z",
                        "offsetOfDomain": -330,
                        "timeZoneName": "Asia/Kolkata",
                        "timezoneIdEventLat": "11.7400867",
                        "timezoneIdEventLng": "92.6586401",
                        "tournamentEvent": true,
                        "offset": 0,
                        "subscriptionTypeDirect": "1",
                        "subscriptionTypeHyper": "0",
                        "hyperLinkValue": "0",
                        "subscriptionTypeMail": "1",
                        "subscriptionTypeMailValue": "testing@gmail.com",
                        "eventsUnderTournament": [
                            "eswnbwBASfYFSY8JA",
                            "FCLpQmeMLQY33J7cQ",
                            "vGX3whvNTSzSp269L",
                            "Q3C5RRa6gzSH5m9Fs",
                            "W56kgzre87hzLuWNP",
                            "o7naQMfvpwRBGNZur",
                            "pX2tRH7Zs2b5huGPX",
                            "5tFmcepy3iwHQ5H6x",
                            "DcKLjSEqKz5oeBdWt",
                            "iALo8Kj2a9nMR2Kea",
                            "A74crML4z9KJjoJFN",
                            "rm4W2dqTi3o4zzbLh",
                            "yT337mphy4EudkHBr",
                            "v4HZkJribFANi4eMM"
                        ],
                        "eventsProjectIdUnderTourn": [
                            "kslkebduo27N2uux7",
                            "kscge09m1u7N2uux7",
                            "ksHHDWReSe7N2uux7",
                            "AJ5LtgFtStmL6KgsD",
                            "H8NKgBHk6JYrycCvf",
                            "tXpQ4DwgrAfFGR4oj",
                            "nPnrTCix3yAD3TmAz",
                            "arGJsShtr9sjRXwyT",
                            "nPnrTCix3yAD3TmAzz",
                            "arGJsShtr9sjRXwyTz",
                            "2XMzYon6GbE9TxmGN",
                            "5ioxxYpoPuox8huWC",
                            "Bn9emodsjqgWEi2pK",
                            "giR4SJEhDJ6mtNGW7"
                        ],
                        "eventCreatedDate": "2020-07-14T03:38:20.473Z",
                        "paymentEntry": "no",
                        "stateAssocId": "k8oK8G2h2KyrddDd8",
                        "allowSubscription": "yes",
                        "source": ""
                    }
                ]
               
